YouTube API_KEY = AIzaSyC-AMcyIgJnJw_AOaOg0HNOrPHLdHgXRnc
Skill Course Hindi - UCnJIjC54FLax9BcAdaGnLHw
Satish Dhawale - UCRDhrUdd9yoVoFFQqadR4FQ
Learn More - UCrHDY6lrJ8NXCKxFppomr3A
Excel Tutorial - UCpZxF2O5dgn0s-du2AnYGOA
Satosh Dhawale English - UCx3WAyIS2jd9noKKRCm8UrA
Satish Tech - UCa-sEIAlqi0C2KuS84MGGfw

Step 1: Setting Up the API Key

Part 1: Retrieving YouTube Channel Details\

let
    API_KEY = "YOUR_API_KEY",
    ChannelIDs = {"UCtxD0x6AuNNqdXO9Wp5GHew", "UCX6OQ3DkcsbYNE6H8uQQuVA"},
    GetChannelDetails = (channel_id as text) =>
    let
        URL = "https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&id=" & channel_id & "&key=" & API_KEY,
        Source = Json.Document(Web.Contents(URL)),
        Items = Source[items]{0},
        Snippet = Items[snippet],
        Statistics = Items[statistics],
        ChannelName = Snippet[title],
        ChannelDescription = Snippet[description],
        CustomURL = try Snippet[customUrl] otherwise "N/A",
        ProfileImage = Snippet[thumbnails][high][url],
        Subscribers = Number.FromText(Statistics[subscriberCount]),
        ChannelThumbnail = Snippet[thumbnails][high][url]
    in
        [ChannelName=ChannelName, ChannelDescription=ChannelDescription, CustomURL=CustomURL, ProfileImage=ProfileImage, Subscribers=Subscribers, ChannelThumbnail=ChannelThumbnail],
    
    ChannelDetails = List.Transform(ChannelIDs, each GetChannelDetails(_)),
    Table = Table.FromRecords(ChannelDetails)
in
    Table


Part 2: Retrieving YouTube Video Details

let
    API_KEY = "YOUR_API_KEY",
    ChannelIDs = {"UCtxD0x6AuNNqdXO9Wp5GHew", "UCX6OQ3DkcsbYNE6H8uQQuVA"},
    MaxResults = 10,
    GetVideoDetails = (channel_id as text) =>
    let
        URL = "https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=" & channel_id & "&order=date&maxResults=" & Number.ToText(MaxResults) & "&key=" & API_KEY,
        Source = Json.Document(Web.Contents(URL)),
        Items = Source[items],
        Videos = List.Transform(Items, each [
            VideoTitle = _[snippet][title],
            VideoDescription = _[snippet][description],
            VideoThumbnail = _[snippet][thumbnails][high][url],
            VideoID = _[id][videoId]
        ]),
        VideoIDs = List.Transform(Videos, each [VideoID]),
        VideoStats = List.Transform(VideoIDs, each GetVideoStatistics(_)),
        MergedList = List.Zip({Videos, VideoStats}),
        Combined = List.Transform(MergedList, each Record.Combine(_))
    in
        Combined,
    
    GetVideoStatistics = (video_id as text) =>
    let
        URL = "https://www.googleapis.com/youtube/v3/videos?part=statistics&id=" & video_id & "&key=" & API_KEY,
        Source = Json.Document(Web.Contents(URL)),
        Statistics = Source[items]{0}[statistics],
        Likes = Number.FromText(Statistics[likeCount]),
        Comments = Number.FromText(Statistics[commentCount]),
        Views = Number.FromText(Statistics[viewCount])
    in
        [Likes=Likes, Comments=Comments, Views=Views],
    
    VideoDetails = List.Combine(List.Transform(ChannelIDs, each GetVideoDetails(_))),
    Table = Table.FromRecords(VideoDetails)
in
    Table

Python Code

Part 1: Youtube Channel Details

import requests

def get_channel_details(channel_ids, api_key):
    channel_data = []
    for channel_id in channel_ids:
        url = f"https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&id={channel_id}&key={api_key}"
        response = requests.get(url)
        data = response.json()
        if 'items' in data and len(data['items']) > 0:
            item = data['items'][0]
            snippet = item['snippet']
            stats = item['statistics']
            channel_data.append({
                'Channel Name': snippet['title'],
                'Channel Description': snippet['description'],
                'Custom URL': snippet.get('customUrl', 'N/A'),
                'Profile Image': snippet['thumbnails']['high']['url'],
                'Subscribers': int(stats.get('subscriberCount', 0)),
                'Channel Thumbnail': snippet['thumbnails']['high']['url']
            })
    return channel_data

# Example usage
channel_ids = ["UCtxD0x6AuNNqdXO9Wp5GHew", "UCX6OQ3DkcsbYNE6H8uQQuVA"]  # MrBeast and Cristiano Ronaldo channels
api_key = 'YOUR_API_KEY'  # Replace with your API key
channel_details = get_channel_details(channel_ids, api_key)
print(channel_details)

Part 2: YoutubeVideo Details

import requests

def get_video_details(channel_ids, api_key, max_results=10):
    video_data = []
    for channel_id in channel_ids:
        # Get the channel name
        channel_url = f"https://www.googleapis.com/youtube/v3/channels?part=snippet&id={channel_id}&key={api_key}"
        channel_response = requests.get(channel_url)
        channel_data = channel_response.json()
        channel_name = channel_data['items'][0]['snippet']['title']
        
        # Get the video details
        url = f"https://www.googleapis.com/youtube/v3/search?part=snippet&channelId={channel_id}&order=date&maxResults={max_results}&key={api_key}"
        response = requests.get(url)
        data = response.json()
        
        for item in data.get('items', []):
            video_id = item['id'].get('videoId', 'N/A')
            if video_id != 'N/A':
                video_snippet = item['snippet']
                video_stats = get_video_statistics(video_id, api_key)
                video_data.append({
                    'Channel Name': channel_name,
                    'Video Title': video_snippet['title'],
                    'Video Description': video_snippet['description'],
                    'Video Thumbnail': video_snippet['thumbnails']['high']['url'],
                    'Video ID': video_id,
                    **video_stats
                })
    return video_data

def get_video_statistics(video_id, api_key):
    url = f"https://www.googleapis.com/youtube/v3/videos?part=statistics&id={video_id}&key={api_key}"
    response = requests.get(url)
    data = response.json()
    
    if 'items' in data and len(data['items']) > 0:
        stats = data['items'][0]['statistics']
        return {
            'Likes': int(stats.get('likeCount', 0)),
            'Comments': int(stats.get('commentCount', 0)),
            'Views': int(stats.get('viewCount', 0))
        }
    return {}

# Example usage
channel_ids = ["UCtxD0x6AuNNqdXO9Wp5GHew", "UCX6OQ3DkcsbYNE6H8uQQuVA"]  # MrBeast and Cristiano Ronaldo channels
api_key = 'YOUR_API_KEY'  # Replace with your API key
video_details = get_video_details(channel_ids, api_key)
print(video_details)